# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11e4563978c9e8b744bd33e59a682a06efd47992bd87a9cacd7250612d360794fb5e8882b37cdd707492a64455e6a941e3f34f4aef9fa1629abef63fb3a3ebb1

test:
  secret_key_base: d6ee644020fc87389bdabd43380c4c93fc378d67735f1ea06767e54b80c7cf07709b9698e2d0b7cddf4f35935f6f7eb06397f31b27053fa0213d063207683090

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
